spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        generate_statistics: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    protocol: jdbc:mysql
    domain: localhost
    port: 3306
    db-name: tcc
    parameters: useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    url: ${spring.datasource.protocol}://${spring.datasource.domain}:${spring.datasource.port}/${spring.datasource.db-name}?${spring.datasource.parameters}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

server:
  port: 9301

logging:
  level:
    root: info
    org:
      springframework: warn
      hibernate:
        sql: warn
        type: warn
    cc.page: debug