spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        generate_statistics: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: 9300

app:
  datasource:
    parameters: useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: &username root
    password: &password 123456
    driver-class-name: &driver-class-name com.mysql.cj.jdbc.Driver
    master: &default-db-config
      url: jdbc:mysql://localhost:3201/test?${app.datasource.parameters}
      username: *username
      password: *password
      driver-class-name: *driver-class-name
      configuration:
        maximum-pool-size: 30
    slave0:
      <<: *default-db-config
      url: jdbc:mysql://localhost:3202/test?${app.datasource.parameters}
    slave1:
      <<: *default-db-config
      url: jdbc:mysql://localhost:3203/test?${app.datasource.parameters}